package commision.core.fileobjectreaders;

import commision.core.entities.pma.Speed;
import commision.core.util.CellParser;

/**
 * Created by radoslaw.wojcik on 2017-11-15.
 */
public class ReadSpeed extends ObjectFileReader<Speed> {
    @Override
    public Speed getRow(String[] row) {
        Speed speed = new Speed();
        String[] headers = getHeaders();
        for(int i = 0; i < headers.length; i++){
            String header = headers[i].toLowerCase().trim();
            String value = row[i];
            switch (header){
                case "zrodlo": { speed.setSource(value); break;}
                case "year": { speed.setYear(value); break;}
                case "month": { speed.setMonth(value); break;}
                case "week": { speed.setWeek(value); break;}
                case "data": { speed.setDate(CellParser.parseStringToDate(value)); break;}
                case "_corr_flg": { speed.setCorr_flg(CellParser.parseStringToInt(value)); break;}
                case "_corr_registration_ids": { speed.setCorrRegistrationIds(value); break;}
                case "_corr_reason": { speed.setCorrReason(value); break;}
                case "abonament_bazowy": { speed.setAbonamentBazowy(CellParser.parseStringToDouble(value)); break;}
                case "abonament_sredni": { speed.setAbonamentSredni(CellParser.parseStringToDouble(value)); break;}
                case "adres_inst_budynek": { speed.setAdresInstBudynek(value); break;}
                case "adres_inst_kod": { speed.setAdresInstKod(value); break;}
                case "adres_inst_miasto": { speed.setAdresInstMiasto(value); break;}
                case "adres_inst_mieszkanie": { speed.setAdresInstMieszkanie(value); break;}
                case "adres_inst_ulica": { speed.setAdresInstUlica(value); break;}
                case "alias_ilosc": { speed.setAliasIlosc(CellParser.parseStringToInt(value)); break;}
                case "alias_wartosc": { speed.setAliasWartosc(CellParser.parseStringToDouble(value)); break;}
                case "data_aktywacji": { speed.setDataAktywacji(value); break;}
                case "data_anulowania": { speed.setDataAnulowania(value); break;}
                case "data_bilingu": { speed.setDataBilingu(value); break;}
                case "data_deaktywacji": { speed.setDataDeaktywacji(value); break;}
                case "data_konca_poprz_umowy": { speed.setDataKoncaPoprzUmowy(value); break;}
                case "data_konca_umowy": { speed.setDataKoncaUmowy(value); break;}
                case "data_poczatku_umowy": { speed.setDataPoczatkuUmowy(value); break;}
                case "data_rejestracji": { speed.setDataRejestracji(value); break;}
                case "data_skompletowania": { speed.setDataSkompletowania(value); break;}
                case "data_umowy": { speed.setDataUmowy(value); break;}
                case "data_wyniku": { speed.setDataWyniku(value); break;}
                case "data_wyniku_poprz": { speed.setDataWynikuPoprz(value); break;}
                case "dostawa_faktury": { speed.setDostawaFaktury(value); break;}
                case "dostawa_sprzetu": { speed.setDostawaSprzetu(value); break;}
                case "dostawa_umowy": { speed.setDostawaUmowy(value); break;}
                case "from_dttm": { speed.setFromDttm(value); break;}
                case "idz": { speed.setIdz(value); break;}
                case "idz_poprz": { speed.setIdzPoprz(value); break;}
                case "id_alias": { speed.setIdAlias(value); break;}
                case "id_di": { speed.setIdDi(value); break;}
                case "id_di_poprz": { speed.setIdDiPoprz(value); break;}
                case "id_di_tr": { speed.setIdDiTr(value); break;}
                case "id_dystryktu": { speed.setIdDystryktu(value); break;}
                case "id_grupy_produktow": { speed.setIdGrupyProduktow(value); break;}
                case "id_kanalu": { speed.setIdKanalu(value); break;}
                case "ch1_name": { speed.setCh1Name(value); break;}
                case "ch2_name": { speed.setCh2Name(value); break;}
                case "ch3_name": { speed.setCh3Name(value); break;}
                case "ch4_name": { speed.setCh4Name(value); break;}
                case "ch5_name": { speed.setCh5Name(value); break;}
                case "ch7_name": { speed.setCh7Name(value); break;}
                case "kanal_rap": { speed.setKanalRap(value); break;}
                case "id_klienta": { speed.setIdKlienta(CellParser.parseStringToLong(value)); break;}
                case "id_partnera": { speed.setIdPartnera(CellParser.parseStringToLong(value)); break;}
                case "id_pos": { speed.setIdPos(CellParser.parseStringToLong(value)); break;}
                case "id_produktu": { speed.setIdProduktu(CellParser.parseStringToLong(value)); break;}
                case "id_regionu": { speed.setIdRegionu(value); break;}
                case "id_sprzedawcy": { speed.setIdSprzedawcy(CellParser.parseStringToLong(value)); break;}
                case "id_sprzedawcy_aktywacji": { speed.setIdSprzedawcyAktywacji(CellParser.parseStringToLong(value)); break;}
                case "id_sprzedawcy_umowy": { speed.setIdSprzedawcyUmowy(CellParser.parseStringToLong(value)); break;}
                case "id_zamowienia": { speed.setIdZamowienia(CellParser.parseStringToLong(value)); break;}
                case "ilosc": { speed.setIlosc(CellParser.parseStringToInt(value)); break;}
                case "kwota_zobowiazania": { speed.setKwotaZobowiazania(CellParser.parseStringToDouble(value)); break;}
                case "liczba_uslug": { speed.setLiczba_uslug(CellParser.parseStringToDouble(value)); break;}
                case "load_id": { speed.setLoadId(CellParser.parseStringToLong(value)); break;}
                case "load_id_first": { speed.setLoadIdFirst(CellParser.parseStringToLong(value)); break;}
                case "model_sprzetu": { speed.setModelSprzetu(value); break;}
                case "nazwa_klienta": { speed.setNazwaKlienta(value); break;}
                case "nazwa_produktu": { speed.setNazwaProduktu(value); break;}
                case "nr_seryjny_sprzetu": { speed.setNrSeryjnySprzetu(value); break;}
                case "numer_ewidencyjny": { speed.setNumerEwidencyjny(value); break;}
                case "numer_uslugi": { speed.setNumerUslugi(value); break;}
                case "numer_zamowienia": { speed.setNumerZamowienia(value); break;}
                case "numer_zamowienia_poprz": { speed.setNumerZamowieniaPoprz(value); break;}
                case "occur_num": { speed.setOccurNum(value); break;}
                case "okres_lojalnosciowy": { speed.setOkresLojalnosciowy(CellParser.parseStringToDouble(value)); break;}
                case "oplata_aktywacyjna": { speed.setOplataAktywacyjna(CellParser.parseStringToDouble(value)); break;}
                case "plan_taryfowy": { speed.setPlanTaryfowy(value); break;}
                case "plan_taryfowy_poprz": { speed.setPlanTaryfowyPoprz(value); break;}
                case "poziom_negocjacji": { speed.setPoziomNegocjacji(value); break;}
                case "predkosc": { speed.setPredkosc(value); break;}
                case "predkosc_poprz": { speed.setPredkoscPoprz(value); break;}
                case "proces": { speed.setProces(value); break;}
                case "produkt_glowny": { speed.setProduktGlowny(value); break;}
                case "typ_bundla": { speed.setTypBundla(value); break;}
                case "promocja": { speed.setPromocja(value); break;}
                case "przyczyna_anulowania": { speed.setPrzyczynaAnulowania(value); break;}
                case "id_segment": { speed.setIdSegment(value); break;}
                case "status_zamowienia": { speed.setStatusZamowienia(value); break;}
                case "system_zrodlowy": { speed.setSystemZrodlowy(value); break;}
                case "typ_zamowienia": { speed.setTypZamowienia(value); break;}
                case "user_id": { speed.setUserId(CellParser.parseStringToLong(value)); break;}
                case "valid_from_dttm": { speed.setValidFromDttm(value); break;}
                case "valid_to_dttm": { speed.setValidToDttm(value); break;}
                case "wartosc": { speed.setWartosc(CellParser.parseStringToDouble(value)); break;}
                case "wartosc_sprzetu": { speed.setWartoscSprzetu(CellParser.parseStringToDouble(value)); break;}
                case "zobowiazanie_miesieczne": { speed.setZobowiazanieMiesieczne(CellParser.parseStringToDouble(value)); break;}
                case "alias": { speed.setAlias(value); break;}
                case "alias_02": { speed.setAlias02(value); break;}
                case "opispoz": { speed.setOpisPoz(value); break;}
                case "chmix": { speed.setChmix(value); break;}
                case "agent": { speed.setAgent(value); break;}
                case "pos_serwus": { speed.setPosSerwus(value); break;}
                case "pos_bscs": { speed.setPosBscs(value); break;}
                case "pos_name": { speed.setPosName(value); break;}
                case "pos_city": { speed.setPosCity(value); break;}
                case "usr_serwus": { speed.setUsrSerwus(value); break;}
                case "usr_nazwisko": { speed.setUsrNazwisko(value); break;}
                case "usr_imie": { speed.setUsrImie(value); break;}
                case "usr_kpx": { speed.setUsrKpx(value); break;}
                case "usr_ifs": { speed.setUsrIfs(value); break;}
                case "usr_bscs": { speed.setUsrBscs(value); break;}
                case "usr_otsa": { speed.setUsrOtsa(value); break;}
                case "segment": { speed.setSegment(value); break;}
                case "id_regionu_str": { speed.setIdRegionuStr(value); break;}
                case "region_str": { speed.setRegionStr(value); break;}
                case "id_dystrykt_str": { speed.setIdDystryktStr(CellParser.parseStringToInt(value)); break;}
                case "dystrykt_str": { speed.setDystryktStr(value); break;}
                case "dm": { speed.setDm(value); break;}
                case "adm": { speed.setAdm(value); break;}
                case "id_segmentu_bud_kli": { speed.setIdSegmentuBudKli(CellParser.parseStringToInt(value)); break;}
                case "id_regionu_kli": { speed.setIdRegionuKli(CellParser.parseStringToInt(value)); break;}
                case "nazwa_regionu_kli": { speed.setNazwaRegionuKli(value); break;}
                case "id_dystrykt_kli": { speed.setIdDystryktKli(CellParser.parseStringToInt(value)); break;}
                case "nazwa_dystryktu_kli": { speed.setNazwaDystryktuKli(value); break;}
                case "nazwa_mikrorynku_kli": { speed.setNazwaMikrorynkuKli(value); break;}
                case "id_lokalizacji_kli": { speed.setIdLokalizacjiKli(CellParser.parseStringToLong(value)); break;}
                case "id_lokalu_kli": { speed.setIdLokaluKli(CellParser.parseStringToLong(value)); break;}
                case "kod_pocztowy_kli": { speed.setKodPocztowyKli(value); break;}
                case "cmc13": { speed.setCmc13(value); break;}
                case "geo_dlugosc": { speed.setGeoDlugosc(value); break;}
                case "geo_szerokosc": { speed.setGeoSzerokosc(value); break;}
                case "murakami_m": { speed.setMurakamiM(value); break;}
                case "flaga_mnp_m": { speed.setFlagaMnpM(value); break;}
                case "nip_m": { speed.setNipM(value); break;}
                case "nr_sieci_m": { speed.setNrSieciM(value); break;}
                case "czy_bezterm_m": { speed.setCzyBeztermM(value); break;}
                case "typ_m": { speed.setTypM(value); break;}
                case "typ2_m": { speed.setTyp2M(value); break;}
                case "rodz_m": { speed.setRodzM(value); break;}
                case "rodz2_m": { speed.setRodz2M(value); break;}
                case "kanal_m": { speed.setKanalM(value); break;}
                case "brand_m": { speed.setBrandM(value); break;}
                case "plany_taryfowy": { speed.setPlanyTaryfowy(value); break;}
                case "migr_zet_m": { speed.setMigrZetM(value); break;}
                case "na_prob_m": { speed.setNaProbM(value); break;}
                case "kod_akt_m": { speed.setKodAktM(value); break;}
                case "id_oferty_m": { speed.setIdOfertM(value); break;}
                case "rata_m": { speed.setRataM(value); break;}
                case "oferta_wylaczona_m": { speed.setOfertaWylaczonaM(value); break;}
                case "migr_zet": { speed.setMigrZet(value); break;}
                case "poziom_negocjacji_m": { speed.setPoziomNegocjacjiM(value); break;}
                case "plany_taryfowy_poprz": { speed.setPlanyTaryfowyPoprz(value); break;}
                case "nazwa_oferty_m": { speed.setNazwaOfertyM(value); break;}
                case "kod_deaktywacji": { speed.setKodDeaktywacji(value); break;}
                case "ilosc_dni_m": { speed.setIloscDniM(value); break;}
                case "numer_telefonu": { speed.setNumerTelefonu(value); break;}
                case "wartosc_subsydia": { speed.setWartoscSubsydia(value); break;}
                case "oplata_lacze": { speed.setOplataLacze(value); break;}
                case "alias_spiu": { speed.setAliasSpiu(value); break;}
                case "numer_zamowienia_m": { speed.setNumerZamowieniaM(value); break;}
                case "id_ofert_m": { speed.setIdOfertM(value); break;}
                case "rule_area_id": { speed.setRuleAreaId(value); break;}
                case "id_mikrorynku_kli": { speed.setIdMikrorynkuKli(value); break;}
                case "_id_user": { speed.setIdUser(value); break;}
                case "_id_punktu": { speed.setIdPunktu(value); break;}
                case "_id_firmy": { speed.setIdFirmy(value); break;}
                case "kanal": { speed.setKanal(value); break;}
                case "zgoda_mkt": { speed.setZgodaMkt(value); break;}
                case "miasto_kli": { speed.setMiastoKli(value); break;}
                case "pickup": { speed.setPickup(value); break;}
                case "voucher": { speed.setVoucher(value); break;}
                case "voucher_id": { speed.setVoucherId(value); break;}
                case "voucher_bonus": { speed.setVoucherBonus(value); break;}
                case "model_secondary": { speed.setModelSecondary(value); break;}
                case "cena_terminala_secondary": { speed.setCenaTerminalaSecondary(value); break;}
                case "id_miejscowosci_kli": { speed.setIdMiejscowosciKli(value); break;}
                case "flaga_vhbb": { speed.setFlagaVhbb(value); break;}
                case "my_orange": { speed.setMyOrange(value); break;}
                case "my_orange_day_no": { speed.setMyOrangeDayNo(value); break;}
                case "my_orange_data": { speed.setMyOrangeData(value); break;}
                case "numer_konta": { speed.setNumerKonta(value); break;}
                case "no": { speed.setNo(value); break;}
                case "zalicz_opl": { speed.setZaliczOpl(value); break;}
                case "zalicz_xrds": { speed.setZaliczXrds(value); break;}
                case "zalicz_xdm": { speed.setZaliczXdm(value); break;}
                case "zalicz_kpos": { speed.setZaliczKpos(value); break;}
                case "zalicz_adm": { speed.setZaliczAdm(value); break;}
                case "zalicz_ph": { speed.setZaliczPh(value); break;}
                case "zalicz_rh": { speed.setZaliczRh(value); break;}
                case "usr_imie_efektywny": { speed.setUsrImieEfektywny(value); break;}
                case "usr_nazwisko_efektywny": { speed.setUsrNazwiskoEfektywny(value); break;}
                case "usr_serwus_efektywny": { speed.setUsrSerwusEfektywny(value); break;}
                case "dystrykt_efektywny": { speed.setDystryktEfektywny(value); break;}
                case "id_dystrykt_efektywny": { speed.setIdDystryktEfektywny(value); break;}
                case "region_efektywny": { speed.setRegionEfektywny(value); break;}
                case "id_regionu_efektywny": { speed.setIdRegionuEfektywny(value); break;}
                case "dystrykt_bgt": { speed.setDystryktBgt(value); break;}
                case "id_dystrykt_bgt": { speed.setIdDystryktBgt(value); break;}
                case "region_bgt": { speed.setRegionBgt(value); break;}
                case "id_regionu_bgt": { speed.setIdRegionuBgt(value); break;}
                case "oferta_wylaczona_oper": { speed.setOfertaWylaczonaOper(value); break;}
                case "oferta_wylaczona_bgt": { speed.setOfertaWylaczonaBgt(value); break;}
                case "kampa_fbb": { speed.setKampaFbb(value); break;}
                case "kampa_lte": { speed.setKampaLte(value); break;}
                case "data_aktualizacji": { speed.setDataAktualizacji(CellParser.parseStringToDate(value)); break;}
                case "segment_buc": { speed.setSegmentBuc(value); break;}
                case "kampania_nazwa": { speed.setKampaniaNazwa(value); break;}
                case "sol": { speed.setSol(value); break;}
                case "strona_namiaru": { speed.setStronaNamiaru(value); break;}
                case "customer_global_id": { speed.setCustomerGlobalId(CellParser.parseStringToLong(value)); break;}
                case "slo_predkosc": { speed.setSloPredkosc(value); break;}
                case "technologia_bb": { speed.setTechnologiaBb(value); break;}
                case "technologia_bb_przed": { speed.setTechnologiaBbPrzed(value); break;}
                case "technologia_bb_po": { speed.setTechnologiaBbPo(value); break;}
            }
        }

        return null;
    }
}
